### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by ming0701** [UBC-MDS/canadacovidmetrics#10]
According to the message below, the package name should have a single, short, all-lowercase name. 
https://github.ubc.ca/mds-2021-22/DSCI_524_collab-sw-dev_students/issues/1

Shall we change it to "canadacovidmetrics"?

**Comment by LukeAC** [comment]
Assigning to @valli180 - this falls under "project structure"

**Comment by valli180** [comment]
Changed it accordingly.
