### ISSUE TITLE
Remove pandas tests from test script

### ISSUE THREAD

**Issue by LukeAC** [UBC-MDS/canadacovidmetrics#23]
Hey @valli180 @ming0701  - noticed a couple of tests that don't seem to line up with the package contents; I've added the screenshots here. Could you please remove them when you get a sec? Thanks!

![image](https://user-images.githubusercontent.com/75291170/150444394-32c770fd-efe1-4e7b-9a94-45b5d0e62e12.png)

![image](https://user-images.githubusercontent.com/75291170/150444425-5d3c519b-1781-4b89-9dc1-022930e120a0.png)

**Comment by ming0701** [comment]
Thanks Luke, I changed the code and created a PR on this.
